# Use an official Ubuntu base image
FROM ubuntu:20.04

# Update the package list and install necessary packages
RUN apt-get update && \
    apt-get -y install python3 python3-pip poppler-utils && \
    apt-get clean

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Run app.py when the container launches
CMD ["python3", "app.py"]
