name: Flask App CI/CD

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.5  # Choose your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Flask App
      env:
        PDF_FILE_PATH: pdf_files/dummy_suket.pdf
      run: python app.py --pdf_path $PDF_FILE_PATH --name "John Doe" --student_id "1234567" --university "Universitas Brawijaya" --publish_1 "Agustus 2021" --publish_2 "September 2021"
