name: Flask App CI/CD

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.5  # Choose your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test Flask App Accessibility
      run: |
        curl http://127.0.0.1:5000/scan_pdf

    # - name: Run Flask App
    #   env:
    #     PDF_FILE_PATH: pdf_files/dummy_suket.pdf
    #     name: ${{ secrets.NAME }}
    #     student_id: ${{ secrets.STUDENT_ID }}
    #     university: ${{ secrets.UNIVERSITY }}
    #     publish_1: ${{ secrets.PUBLISH_1 }}
    #     publish_2: ${{ secrets.PUBLISH_2 }}
    #   run: |
    #     python app.py --pdf_path $PDF_FILE_PATH