name: Flask App CI/CD

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.5  # Choose your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set File Permissions
      run: |
        chmod +r pdf_files/dummy-suket.pdf

    - name: Run Flask App
      # env:
      #   PDF_FILE_PATH: pdf_files/dummy-suket.pdf
      #   NAME: ${{ secrets.NAME }}
      #   STUDENT_ID: ${{ secrets.STUDENT_ID }}
      #   UNIVERSITY: ${{ secrets.UNIVERSITY }}
      #   PUBLISH_1: ${{ secrets.PUBLISH_1 }}
      #   PUBLISH_2: ${{ secrets.PUBLISH_2 }}
      run: |
        python app.py &

    - name: Test Flask App Accessibility
      run: |
        curl -X POST \
          -F "file=@$pdf_files/dummy-suket.pdf" \
          -F "name=John Doe" \
          -F "student_id=1234567" \
          -F "university=Universitas Brawijaya" \
          -F "publish_1=Agustus 2021" \
          -F "publish_2=September 2021" \
          http://127.0.0.1:5000/scan_pdf



