name: Flask App CI/CD

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Choose your Python version

    - name: Install Poppler
      run: sudo apt-get install poppler-utils

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set File Permissions
      run: |
        chmod +r pdf_files/dummy-suket-september.pdf

    - name: Run Flask App
      run: |
        python app.py &

    - name: Test Flask App Accessibility
      run: |
        curl -X POST \
          -F "file=@pdf_files/dummy-suket-september.pdf" \
          -F "name=John Doe" \
          -F "student_id=123456" \
          -F "university=Universitas Brawijaya" \
          http://127.0.0.1:5000/scan_pdf



